name: Changelog Check

on:
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened, ready_for_review, labeled, unlabeled ]

permissions: {}

jobs:
  changelog:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read

    steps:
      - name: Ensure changelog is updated or explicitly skipped
        uses: dangoslen/changelog-enforcer@8b5e9dc3121363bb7c0115f8533404d92af382de # v3.7.0
        with:
          changeLogPath: CHANGELOG.md
          skipLabels: skip-changelog
          missingUpdateErrorMessage: "Pull requests must update CHANGELOG.md, or use the skip-changelog label to bypass this check."